version: '3.2'
services:
    mysql:
        image: mysql:5
        command: --default-authentication-plugin=mysql_native_password --sql-mode="STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION"
        environment:
            MYSQL_ROOT_PASSWORD: root
            TZ: America/Sao_Paulo
        stdin_open: true
        volumes:
            - ./docker/mysql:/var/lib/mysql
        tty: true
        ports:
            - 3306:3306
    api:
        hostname: api
        build: .
        ports:
            - 8080:8080
        volumes:
            - .:/src
        links:
            - mysql
